### ISSUE TITLE
[BUG] Rofi not becoming transparent on Hyprland

### ISSUE THREAD

**Issue by HydraJkm** [lbonn/rofi#146]
### Rofi version (rofi -v or git commit in case of build issue)

1.7.5+wayland3

### Configuration

https://gist.github.com/HydraJkm/b7a1905a562090ac7a39b44d3fac0986

### Theme

https://gist.github.com/HydraJkm/b7a1905a562090ac7a39b44d3fac0986

### Timing report

https://gist.github.com/HydraJkm/b7a1905a562090ac7a39b44d3fac0986

### Launch command

rofi -show drun

### Step to reproduce

* vim ~/.config/rofi/config.rasi
* i @theme "homedir/.config/rofithemes/mytheme.rasi"
(homedir is your user's home directory (e.g. /home/user))
* esc :wq
* mkdir ~/.config/rofithemes
* vim ~/.config/rofithemes/mytheme.rasi
* i  
```
window {
transparency: "real";
background-color: rgba(255,0,0,50%);
}
entry {
background-color: rgba(255,0,0,50%);
}
```
* esc :wq
* rofi -show drun

### Expected behavior

Red background with 50% transparency showing through to whatever is behind it.

### Actual behavior

Light red background on entry, no transparency.

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by lbonn** [comment]
@HydraJkm maybe it's something with your theme?

Does it work with one of the default themes that uses transparency?
Like [arthur.rasi](https://github.com/lbonn/rofi/blob/wayland/themes/arthur.rasi)

**Comment by Caellian** [comment]
I haven't experienced similar issues on Hyprland, and have been using this for over a year.

Here's my theme for comparison:
<details>

```css
/**
 *
 * Author : Aditya Shakya (adi1090x)
 * Github : @adi1090x
 * 
 * Rofi Theme File
 * Rofi Version: 1.7.3
 **/

/*****----- Configuration -----*****/
configuration {
	modi:                       "drun";
    show-icons:                 true;
    display-drun:               "";
	drun-display-format:        "{name}";
}

/*****----- Global Properties -----*****/
* {
    background:     #323D43FF;
    background-alt: #3C474DFF;
    foreground:     #DAD1BEFF;
    selected:       #7FBBB3FF;
    active:         #A7C080FF;
    urgent:         #E67E80FF;
    font:           "Hack Nerd Font 14";
}

/*****----- Main Window -----*****/
window {
    transparency:                "real";
    location:                    center;
    anchor:                      center;
    fullscreen:                  true;
    width:                       1920px;
    height:                      1080px;
    x-offset:                    0px;
    y-offset:                    0px;

    enabled:                     true;
    margin:                      0px;
    padding:                     0px;
    border:                      0px solid;
    border-radius:               0px;
    border-color:                @selected;
    background-color:            black / 90%;
    cursor:                      "default";
}

/*****----- Main Box -----*****/
mainbox {
    enabled:                     true;
    spacing:                     100px;
    margin:                      0px;
    padding:                     100px 225px;
    border:                      0px solid;
    border-radius:               0px 0px 0px 0px;
    border-color:                @selected;
    background-color:            transparent;
    children:                    [ "inputbar", "listview" ];
}

/*****----- Inputbar -----*****/
inputbar {
    enabled:                     true;
    spacing:                     10px;
    margin:                      0% 25%;
    padding:                     18px;
    border:                      0px solid;
    border-radius:               10px;
    border-color:                @selected;
    background-color:            white / 5%;
    text-color:                  @foreground;
    children:                    [ "prompt", "entry" ];
}

prompt {
    enabled:                     true;
    background-color:            transparent;
    text-color:                  inherit;
}
textbox-prompt-colon {
    enabled:                     true;
    expand:                      false;
    str:                         "::";
    background-color:            transparent;
    text-color:                  inherit;
}
entry {
    enabled:                     true;
    background-color:            transparent;
    text-color:                  inherit;
    cursor:                      text;
    placeholder:                 "Search";
    placeholder-color:           inherit;

}

/*****----- Listview -----*****/
listview {
    enabled:                     true;
    columns:                     8;
    lines:                       4;
    cycle:                       true;
    dynamic:                     true;
    scrollbar:                   false;
    layout:                      vertical;
    reverse:                     false;
    fixed-height:                true;
    fixed-columns:               true;
    
    spacing:                     10px;
    margin:                      0px;
    padding:                     0px;
    border:                      0px solid;
    border-radius:               0px;
    border-color:                @selected;
    background-color:            transparent;
    text-color:                  @foreground;
    cursor:                      "default";
}
scrollbar {
    handle-width:                5px ;
    handle-color:                @selected;
    border-radius:               0px;
    background-color:            @background-alt;
}

/*****----- Elements -----*****/
element {
    enabled:                     true;
    spacing:                     15px;
    margin:                      0px;
    padding:                     30px 10px;
    border:                      0px solid;
    border-radius:               10px;
    border-color:                @selected;
    background-color:            transparent;
    text-color:                  @foreground;
    orientation:                 vertical;
    cursor:                      pointer;
}
element normal.normal, element alternate.normal {
    background-color:            transparent;
    text-color:                  @foreground;
}
element selected.normal {
    background-color:            white / 5%;
    text-color:                  @foreground;
}
element-icon {
    background-color:            transparent;
    text-color:                  inherit;
    size:                        72px;
    cursor:                      inherit;
}
element-text {
    background-color:            transparent;
    text-color:                  inherit;
    highlight:                   inherit;
    cursor:                      inherit;
    vertical-align:              0.5;
    horizontal-align:            0.5;
}

/*****----- Message -----*****/
error-message {
    padding:                     100px;
    border:                      0px solid;
    border-radius:               0px;
    border-color:                @selected;
    background-color:            black / 10%;
    text-color:                  @foreground;
}
textbox {
    background-color:            transparent;
    text-color:                  @foreground;
    vertical-align:              0.5;
    horizontal-align:            0.0;
    highlight:                   none;
}
```

</details>
