### ISSUE TITLE
[BUG] -click-to-exit not working

### ISSUE THREAD

**Issue by ram02z** [lbonn/rofi#22]
## Version

Output of `rofi -v`
`1.6.1-wayland`

## Configuration
Output of `rofi -help` (in a [gist](https://gist.github.com/), please paste the *full* output)
https://gist.github.com/ram02z/07c7888924bbe35068d7c3883b308c55

## Launch Command

`The commandline used to launch **rofi**`
`rofi -show`

## Steps to reproduce

- Step 1: run `rofi -click-to-exit -show`
- Step 2: Press outside of the rofi window

## What behaviour you see
Nothing happens. Excuse my ignorance, but is this expected due to how wayland works?

## What behaviour you expect to see
The rofi window closes.

**Additional details:**
The issue persists with the default config.

**Please do not submit reports related to wayland, see
[here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
information.**

**Comment by lbonn** [comment]
Indeed, that's difficult to implement as is, as pointer events outside of the target surface are not sent by design in wayland.

It could maybe work if we'd reserve a layer covering the complete screen but only show the rofi window in a limited area. This way, we'd get mouse events anywhere. But that sounds a bit hacky and may be tricky with multi-monitors...

Another trick (maybe) would be to add an option to exit on pointer leave (in wl_pointer_listener) and have your compositor focus on click. Also weird

Otherwise, I think it would need some additional supports in protocols or compositor-specific.

I'll leave the bug open in case somebody has a great idea for this.

**Comment by ghost** [comment]
Another idea (deviates a bit from standard rofi): optionally make the `#window` clickable, use the mainbox for actual content (that's how I do it to get a nice fullscreen overlay behind the actual "menu")

```yml
window:
  background-color: "#YONICE"
  children: "[mainbox]"
  fullscreen: true
  padding: 0 80% 0 0      # <------ use this for positioning instead of rofi's anchors 

mainbox:
  background-color: "#D000D3"
  children: "[this, and, that]"
  expand: true

[...]
```
